LIBGLIB2_VERSION_MAJOR = 2.67
LIBGLIB2_VERSION = $(LIBGLIB2_VERSION_MAJOR).2
LIBGLIB2_SOURCE = glib-$(LIBGLIB2_VERSION).tar.xz
LIBGLIB2_SITE = http://ftp.gnome.org/pub/gnome/sources/glib/$(LIBGLIB2_VERSION_MAJOR)

LIBGLIB2_DEPENDENCIES=pkgconf libffi libzlib

LIBGLIB2_CONF_ENV =

LIBGLIB2_CONF_OPTS=

$(eval $(meson-package))
