GLIB_NETWORKING_VERSION_MAJOR = 2.64
GLIB_NETWORKING_VERSION = $(GLIB_NETWORKING_VERSION_MAJOR).3
GLIB_NETWORKING_SOURCE = glib-networking-$(GLIB_NETWORKING_VERSION).tar.xz
GLIB_NETWORKING_SITE = http://ftp.gnome.org/pub/gnome/sources/glib-networking/$(GLIB_NETWORKING_VERSION_MAJOR)

GLIB_NETWORKING_DEPENDENCIES=pkgconf gnutls

GLIB_NETWORKING_CONF_ENV =

GLIB_NETWORKING_CONF_OPTS=-Dlibproxy=disabled

$(eval $(meson-package))
