OPENCV_VERSION = 4.5.2
OPENCV_SOURCE = $(OPENCV_VERSION).tar.gz
OPENCV_SOURCE_NAME = opencv-$(OPENCV_VERSION)
OPENCV_SITE = https://github.com/opencv/opencv/archive/refs/tags

OPENCV_DEPENDENCIES=ffmpeg

OPENCV_CONF_OPTS=-DCMAKE_BUILD_TYPE=Release -DENABLE_PRECOMPILED_HEADERS=OFF -DCMAKE_SHARED_LINKER_FLAGS="-shared" -DBUILD_TESTS=OFF -DWITH_FFMPEG=ON -DFFMPEG_INCLUDE_DIRS=$(INSTALL_DIR)/include -DOPENCV_GENERATE_PKGCONFIG=ON

$(eval $(cmake-package))
