WAYLAND_PROTOCOLS_VERSION = 1.8
WAYLAND_PROTOCOLS_SOURCE = wayland-protocols-$(WAYLAND_PROTOCOLS_VERSION).tar.xz
WAYLAND_PROTOCOLS_SITE =  https://wayland.freedesktop.org/releases/

WAYLAND_PROTOCOLS_DEPENDENCIES=

WAYLAND_PROTOCOLS_CONF_OPTS=

